export enum constants {
  GET_ALL_SHOPITEMS = "GET_ALL_SHOPITEMS",
  UPDATE_SHOP_ITEM = "UPDATE_SHOP_ITEM",
  ADD_CART_ITEM = "ADD_CART_ITEM",
  UPDATE_CART_ITEM = "UPDATE_CART_ITEM",
  DELETE_CART_ITEM = "DELETE_CART_ITEM",
}
